language: node_js
node_js:
 - "node"

script:
  - npm test

deploy:
  provider: script
  # script: chmod +x deploy.js && node deploy.js 
  script: bash deploy.sh
  on:
    branch: master
  skip_cleanup: true



