language: node_js
node_js:
 - "node"

before_install:
  - npm install --silent
#script:
  #- npm test
deploy:
  provider: script
  script: node deploy.js
  #skip_cleanup: true
  on:
    branch: master



