language: node_js
node_js:
 - "node"

git:
  depth: false

before_deploy:
  - npm install -g --silent

deploy:
  provider: script
  script: node deploy.js
  #skip_cleanup: true
  on:
    branch: master



