language: node_js
node_js:
 - "node"

before_deploy:
  - npm install -g --silent

deploy:
  provider: script
  script: node deploy.js
  #skip_cleanup: true
  on:
    branch: master
  provider: script
  script: "bash ls -la"
  on:
    branch: master


addons:
  artifacts: 
    debug: true
    bucket: travis-ci-artifact-bucket
    s3_region: us-east-1